//! Parser for the VisioTalk DSL.
//! The grammar is defined in `src/grammar.lalrpop` and compiled by LALRPOP.

// This module will be generated by LALRPOP at build time.
// Uncomment once the grammar file is created:
// lalrpop_mod!(pub grammar);

/// Parses a VisioTalk source string into an AST.
pub fn parse(_source: &str) -> Result<vt_core::Program, String> {
    // Placeholder — will be replaced by generated parser once grammar.lalrpop exists.
    Err("Parser not yet implemented — grammar.lalrpop needed".into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_empty() {
        assert!(parse("").is_err());
    }
}
